/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacecompleta;

import javax.swing.JOptionPane;

/**
 *
 * @author Henrique Mendes
 */
public class JanelaAjuda extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaAjuda
     */
    public JanelaAjuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotaoJanelaAjuda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ReportarProblemasAjuda = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("AJUDA");

        BotaoJanelaAjuda.setText("Reportar");
        BotaoJanelaAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoJanelaAjudaActionPerformed(evt);
            }
        });

        jLabel2.setText("Reportar problemas");

        ReportarProblemasAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportarProblemasAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(BotaoJanelaAjuda)
                    .addComponent(jLabel2)
                    .addComponent(ReportarProblemasAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportarProblemasAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(BotaoJanelaAjuda)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoJanelaAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoJanelaAjudaActionPerformed
        
        Cliente ajuda = new Cliente();
        
        ajuda.setReportProblemaAjuda(ReportarProblemasAjuda.getText());
        
        JOptionPane.showMessageDialog(null, ajuda.salvarAjuda());
    }//GEN-LAST:event_BotaoJanelaAjudaActionPerformed

    private void ReportarProblemasAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportarProblemasAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportarProblemasAjudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoJanelaAjuda;
    private javax.swing.JTextField ReportarProblemasAjuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
