/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacecompleta;

import javax.swing.JOptionPane;

/**
 *
 * @author Henrique Mendes
 */
public class JanelaRelatorioDeClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaRelatorioDeCliente
     */
    public JanelaRelatorioDeClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeRelatorioDeClientes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CPFRelatorioDeClientes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EstadoCivilRelatorioDeClientes = new javax.swing.JTextField();
        BotaoSalvarRelatorioDeClientes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("RELATÓRIO DE CLIENTES");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Estado civil");

        BotaoSalvarRelatorioDeClientes.setText("Salvar");
        BotaoSalvarRelatorioDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarRelatorioDeClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(NomeRelatorioDeClientes)
                        .addComponent(jLabel3)
                        .addComponent(CPFRelatorioDeClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(EstadoCivilRelatorioDeClientes))
                    .addComponent(BotaoSalvarRelatorioDeClientes))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeRelatorioDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPFRelatorioDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstadoCivilRelatorioDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoSalvarRelatorioDeClientes)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSalvarRelatorioDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarRelatorioDeClientesActionPerformed
        
        Cliente Ralatclientes = new Cliente();
        
        Ralatclientes.setNomeRelatoClientes(NomeRelatorioDeClientes.getText());
        Ralatclientes.setCPFRelatoCliente(CPFRelatorioDeClientes.getText());
        Ralatclientes.setEstadoCivRelatoCliente(EstadoCivilRelatorioDeClientes.getText());
        
        JOptionPane.showMessageDialog(null, Ralatclientes.salvarRelatorioClientes());
    }//GEN-LAST:event_BotaoSalvarRelatorioDeClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvarRelatorioDeClientes;
    private javax.swing.JTextField CPFRelatorioDeClientes;
    private javax.swing.JTextField EstadoCivilRelatorioDeClientes;
    private javax.swing.JTextField NomeRelatorioDeClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
