/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacecompleta;

import javax.swing.JOptionPane;

/**
 *
 * @author Henrique Mendes
 */
public class JanelaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaInterna
     */
    public JanelaInterna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NomeJanelaInterna = new javax.swing.JTextField();
        BotaoSalvarJanelaInterna = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RuaJanelaInterna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BairroJanelaInterna = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Nome");

        NomeJanelaInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeJanelaInternaActionPerformed(evt);
            }
        });

        BotaoSalvarJanelaInterna.setText("Salvar");
        BotaoSalvarJanelaInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarJanelaInternaActionPerformed(evt);
            }
        });

        jLabel2.setText("Rua");

        jLabel3.setText("Bairro");

        BairroJanelaInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroJanelaInternaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(NomeJanelaInterna, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                        .addComponent(RuaJanelaInterna)
                        .addComponent(BairroJanelaInterna))
                    .addComponent(BotaoSalvarJanelaInterna))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeJanelaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RuaJanelaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BairroJanelaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BotaoSalvarJanelaInterna)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeJanelaInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeJanelaInternaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeJanelaInternaActionPerformed

    private void BairroJanelaInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroJanelaInternaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroJanelaInternaActionPerformed

    private void BotaoSalvarJanelaInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarJanelaInternaActionPerformed
        
        Cliente Cadcliente = new Cliente();
        
        Cadcliente.setNomeInterno(NomeJanelaInterna.getText());
        Cadcliente.setRuaInterno(RuaJanelaInterna.getText());
        Cadcliente.setBairroInterno(BairroJanelaInterna.getText());
        
        JOptionPane.showMessageDialog(null, Cadcliente.salvaInterno());
    }//GEN-LAST:event_BotaoSalvarJanelaInternaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroJanelaInterna;
    private javax.swing.JButton BotaoSalvarJanelaInterna;
    private javax.swing.JTextField NomeJanelaInterna;
    private javax.swing.JTextField RuaJanelaInterna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
